### ISSUE TITLE
Command 'MAUI Archive: Android - List of Keystores & Check Signature' resulted in error

### ISSUE THREAD

**Issue by GeorgeLeithead** [banditoth/maui-archiver-vscode#3]
I've installed your extension onto VS CODE.  I have then opened a .NET MAUI project/folder, and using the 

1. I open my .NET MAUI project in Visual Studio Code.
1. Access the Command Palette (Ctrl+Shift+P).
1. Used the command `MAUI Archive: Android - List of Keystores & Check Signature`

I get the following error:
![image](https://github.com/banditoth/maui-archiver-vscode/assets/43666574/19d5c640-b72d-496b-a476-e844b9917835)

Error: ENOENT: no such file or directory, scandir 'c:\ProgramData\Xamarin\Mono for Android'.

My keystore is at the following path, and I can successfully use any keystore here to sign my distributions:
C:\Users\<my user>\AppData\Local\Xamarin\Mono for Android\Keystore

Using Visual Studio and distribute an archive, I get the list of keystores:
![Untitled](https://github.com/banditoth/maui-archiver-vscode/assets/43666574/1b3cc4ae-6b55-47d4-88b5-b2c5767dd67f)

**Comment by GeorgeLeithead** [comment]
I tried using the command "MAUI Archive Settings", but only get the following settings:
![image](https://github.com/banditoth/maui-archiver-vscode/assets/43666574/0db30ff9-ba2e-4471-ae2e-df86c485882f)

**Comment by banditoth** [comment]
Hey @GeorgeLeithead 
Thanks for giving feedback!
I had no idea that people would start using the extension so quickly. Unfortunately I haven't had the chance to fully test the extension on windows yet, but I'm working on it. It seems that the burned in path to the Xamarin keystore files is wrong on windows. However, you're looking in the right place, I'll post a configuration option soon to override this path and fix it so that it points to the right place in the default path.

Stay tuned, it will be fixed today or tomorrow.

**Comment by GeorgeLeithead** [comment]
> Hey @GeorgeLeithead Thanks for giving feedback! I had no idea that people would start using the extension so quickly. Unfortunately I haven't had the chance to fully test the extension on windows yet, but I'm working on it. It seems that the burned in path to the Xamarin keystore files is wrong on windows. However, you're looking in the right place, I'll post a configuration option soon to override this path and fix it so that it points to the right place in the default path.
> 
> Stay tuned, it will be fixed today or tomorrow.

I blame @jfversluis for his highly effective marketing campaign on X, LinkedIn, etc...

I can confirm that I am indeed on Windows 11, when I experience the issue.

The path where my keystore is located, I *believe* is the default on Windows, and is `user` specific.

**Comment by banditoth** [comment]
Hey @GeorgeLeithead 

Seems like the problem have been fixed in version 0.1.3. Could you please check it out?
Also you can override the default path in the settings now.

<img width="1198" alt="image" src="https://github.com/banditoth/maui-archiver-vscode/assets/24568882/0e1b71f2-dc0a-4518-83d2-576eccb482ca">
